backend = "glx";
# backend = "xrender";

vsync = false;
use-damage = true;

corner-radius = 12;

# unredir-if-possible = true;

# --- Blur  ---
# blur-background = false;

blur: {
  method = "dual_kawase";
  strength = 5;
  background = true;
  background-frame = false;
  background-fixed = false;
}

opacity-rule = [
  "80:class_g = 'Thunar'",
  "80:class_g = 'dolphin'",
  "80:class_g = 'Sublime_text'",
  "80:class_g = 'kitty'",
  "80:class_g = 'Xfce4-terminal'",
  "80:class_g = 'Gnome-terminal'"
];

# --- Shadow ---
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;

# --- Fading ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;


rounded-corners-exclude = [
#   "window_type = 'dock'",
   "window_type = 'desktop'",
#   "class_g = 'i3-frame'"
 ];